export enum EInvalidationTags {
  AUTH = 'auth',
  REGISTRATION = 'registration',
  CLIENT = 'client',
  CHILD = 'child',
  COUPLE = 'couple',
  MEET = 'meet',
  MEET_ID = 'meet_id',
  METHOD = 'method',
  MEET_METHOD = 'meet_method',
  ACCOUNT = 'account',
  ACCOUNT_INFO = 'account_info',
  QUESTIONNAIRES = 'questionnaires',
  QUESTIONNAIRES_CLIENT = 'questionnaires_client',
  CALENDAR = 'calendar',
  NOTIFICATIONS = 'notifications',
}
